MAX_FAILED_PER_TYPE = {
    "pink": {
        "invalid_user": 10,
        "failed_attempt": 7,
        "unknown": 5,
        "session_opened": 20,
        "session_closed": 20,
        "successful_login": 20,
    },
    "blue": {
        "invalid_user": 8,
        "failed_attempt": 5,
        "unknown": 4,
        "session_opened": 15,
        "session_closed": 15,
        "successful_login": 15,
    },
    "red": {
        "invalid_user": 5,
        "failed_attempt": 3,
        "unknown": 3,
        "session_opened": 10,
        "session_closed": 10,
        "successful_login": 10,
    },
    "violet": {
        "invalid_user": 3,
        "failed_attempt": 2,
        "unknown": 2,
        "session_opened": 8,
        "session_closed": 8,
        "successful_login": 8,
    },
    "darkred": {
        "invalid_user": 2,
        "failed_attempt": 1,
        "unknown": 1,
        "session_opened": 5,
        "session_closed": 5,
        "successful_login": 5,
    },
    "black": {
        "invalid_user": 1,
        "failed_attempt": 1,
        "unknown": 1,
        "session_opened": 3,
        "session_closed": 3,
        "successful_login": 3,
    },
}

ACTIONS_PER_THREAT_LEVEL_PER_TYPE = {
    "pink": {
        "invalid_user": {"action": "BAN", "duration": 3600},
        "failed_attempt": {"action": "BAN", "duration": 1800},
        "unknown": {"action": "ALERT", "duration": 0},
        "session_opened": {"action": "NO_ACTION", "duration": 0},
        "session_closed": {"action": "NO_ACTION", "duration": 0},
        "successful_login": {"action": "NO_ACTION", "duration": 0},
    },
    "blue": {
        "invalid_user": {"action": "BAN", "duration": 7200},
        "failed_attempt": {"action": "BAN", "duration": 3600},
        "unknown": {"action": "ALERT", "duration": 0},
        "session_opened": {"action": "NO_ACTION", "duration": 0},
        "session_closed": {"action": "NO_ACTION", "duration": 0},
        "successful_login": {"action": "NO_ACTION", "duration": 0},
    },
    "red": {
        "invalid_user": {"action": "BAN", "duration": 14400},
        "failed_attempt": {"action": "BAN", "duration": 7200},
        "unknown": {"action": "ALERT", "duration": 0},
        "session_opened": {"action": "NO_ACTION", "duration": 0},
        "session_closed": {"action": "NO_ACTION", "duration": 0},
        "successful_login": {"action": "NO_ACTION", "duration": 0},
    },
    "violet": {
        "invalid_user": {"action": "BAN", "duration": 28800},
        "failed_attempt": {"action": "BAN", "duration": 14400},
        "unknown": {"action": "ALERT", "duration": 0},
        "session_opened": {"action": "NO_ACTION", "duration": 0},
        "session_closed": {"action": "NO_ACTION", "duration": 0},
        "successful_login": {"action": "NO_ACTION", "duration": 0},
    },
    "darkred": {
        "invalid_user": {"action": "BAN", "duration": 43200},
        "failed_attempt": {"action": "BAN", "duration": 2419200},
        "unknown": {"action": "ALERT", "duration": 0},
        "session_opened": {"action": "NO_ACTION", "duration": 0},
        "session_closed": {"action": "NO_ACTION", "duration": 0},
        "successful_login": {"action": "NO_ACTION", "duration": 0},
    },
    "black": {
        "invalid_user": {"action": "BAN", "duration": 0},
        "failed_attempt": {"action": "BAN", "duration": 0},
        "unknown": {"action": "ALERT", "duration": 0},
        "session_opened": {"action": "NO_ACTION", "duration": 0},
        "session_closed": {"action": "NO_ACTION", "duration": 0},
        "successful_login": {"action": "NO_ACTION", "duration": 0},
    },
}
